version: '3.8'

services:
  api_gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - DATABASE_URL=mysql+mysqlconnector://user:password@db/microservices_db
    depends_on:
      - db

  random_number:
    build:
      context: .
      dockerfile: random_number/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - db

  even_odd:
    build:
      context: .
      dockerfile: even_odd/Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: microservices_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
