services:
  db_random_number:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: random_number_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

  db_even_odd:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: even_odd_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"

  db_api_gateway:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: api_gateway_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"

  random_number:
    build:
      context: .
      dockerfile: random_number/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mysql://user:password@db_random_number/random_number_db
    depends_on:
      - db_random_number

  even_odd:
    build:
      context: .
      dockerfile: even_odd/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=mysql://user:password@db_even_odd/even_odd_db
    depends_on:
      - db_even_odd

  api_gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://user:password@db_api_gateway/api_gateway_db
    depends_on:
      - db_api_gateway
      - random_number
      - even_odd
